[2024-12-26T21:16:19.565+0000] {processor.py:153} INFO - Started process (PID=48239) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:16:19.567+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:16:19.569+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:16:19.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:16:19.705+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:16:19.672+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:16:19.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:16:19.849+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.295 seconds
[2024-12-26T21:16:50.231+0000] {processor.py:153} INFO - Started process (PID=48323) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:16:50.232+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:16:50.234+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:16:50.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:16:50.250+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:16:50.249+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:16:50.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:16:50.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.036 seconds
[2024-12-26T21:17:21.058+0000] {processor.py:153} INFO - Started process (PID=48414) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:17:21.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:17:21.063+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:17:21.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:17:21.081+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:17:21.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:17:21.082+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:17:21.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.041 seconds
[2024-12-26T21:17:51.841+0000] {processor.py:153} INFO - Started process (PID=48498) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:17:51.842+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:17:51.843+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:17:51.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:17:51.854+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:17:51.853+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:17:51.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:17:51.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.024 seconds
[2024-12-26T21:18:22.458+0000] {processor.py:153} INFO - Started process (PID=48580) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:18:22.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:18:22.460+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:18:22.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:18:22.472+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:18:22.471+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:18:22.473+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:18:22.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.027 seconds
[2024-12-26T21:18:53.213+0000] {processor.py:153} INFO - Started process (PID=48675) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:18:53.214+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:18:53.214+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:18:53.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:18:53.232+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:18:53.231+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:18:53.232+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:18:53.245+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.036 seconds
[2024-12-26T21:19:23.818+0000] {processor.py:153} INFO - Started process (PID=48766) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:19:23.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:19:23.820+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:19:23.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:19:23.837+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:19:23.835+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:19:23.837+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:19:23.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.036 seconds
[2024-12-26T21:19:54.424+0000] {processor.py:153} INFO - Started process (PID=48857) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:19:54.425+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:19:54.425+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:19:54.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:19:54.436+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:19:54.435+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:19:54.436+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:19:54.473+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.051 seconds
[2024-12-26T21:20:24.996+0000] {processor.py:153} INFO - Started process (PID=48932) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:20:24.997+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:20:24.997+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:20:24.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:20:25.013+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:20:25.012+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:20:25.014+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:20:25.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.033 seconds
[2024-12-26T21:20:55.571+0000] {processor.py:153} INFO - Started process (PID=49023) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:20:55.572+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:20:55.572+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:20:55.572+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:20:55.580+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:20:55.579+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:20:55.580+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:20:55.588+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.018 seconds
[2024-12-26T21:21:26.261+0000] {processor.py:153} INFO - Started process (PID=49113) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:21:26.262+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:21:26.262+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:21:26.262+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:21:26.278+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:21:26.277+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:21:26.278+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:21:26.316+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.059 seconds
[2024-12-26T21:21:56.696+0000] {processor.py:153} INFO - Started process (PID=49202) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:21:56.697+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:21:56.697+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:21:56.697+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:21:56.707+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:21:56.706+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:21:56.707+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:21:56.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.021 seconds
[2024-12-26T21:22:27.160+0000] {processor.py:153} INFO - Started process (PID=49277) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:22:27.161+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:22:27.162+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:27.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:22:27.179+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:27.178+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 10, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 539, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 186, in create_timetable
    raise ValueError(f"{interval!r} is not a valid schedule_interval.")
ValueError: [Dataset(uri='/tmp/file.txt', extra=None)] is not a valid schedule_interval.
[2024-12-26T21:22:27.179+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:22:27.192+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.035 seconds
[2024-12-26T21:22:51.614+0000] {processor.py:153} INFO - Started process (PID=49368) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:22:51.615+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:22:51.615+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:51.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:22:51.627+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:22:51.676+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:51.675+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:consumer
[2024-12-26T21:22:51.679+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:51.679+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:consumer
[2024-12-26T21:22:51.681+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:51.680+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:consumer
[2024-12-26T21:22:51.681+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:51.681+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:22:51.686+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:51.686+0000] {dag.py:2711} INFO - Creating ORM DAG for consumer
[2024-12-26T21:22:51.690+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:22:51.690+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:22:51.767+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.155 seconds
[2024-12-26T21:23:22.107+0000] {processor.py:153} INFO - Started process (PID=49443) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:23:22.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:23:22.109+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:23:22.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:23:22.123+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:23:22.136+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:23:22.136+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:23:22.147+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:23:22.147+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:23:22.156+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.051 seconds
[2024-12-26T21:23:52.526+0000] {processor.py:153} INFO - Started process (PID=49534) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:23:52.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:23:52.527+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:23:52.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:23:52.543+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:23:52.556+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:23:52.556+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:23:52.567+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:23:52.567+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:23:52.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.054 seconds
[2024-12-26T21:24:22.924+0000] {processor.py:153} INFO - Started process (PID=49625) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:24:22.925+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:24:22.926+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:24:22.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:24:22.944+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:24:22.961+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:24:22.961+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:24:22.972+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:24:22.971+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:24:22.981+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.062 seconds
[2024-12-26T21:24:53.367+0000] {processor.py:153} INFO - Started process (PID=49716) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:24:53.367+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:24:53.367+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:24:53.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:24:53.379+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:24:53.393+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:24:53.393+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:24:53.406+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:24:53.406+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:24:53.416+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.051 seconds
[2024-12-26T21:25:23.965+0000] {processor.py:153} INFO - Started process (PID=49791) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:25:23.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:25:23.966+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:25:23.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:25:23.985+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:25:24.002+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:25:24.002+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:25:24.014+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:25:24.013+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:25:24.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.062 seconds
[2024-12-26T21:41:18.561+0000] {processor.py:153} INFO - Started process (PID=49864) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:41:18.562+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:41:18.563+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:41:18.562+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:41:18.588+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:41:18.617+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:41:18.616+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:41:18.651+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:41:18.651+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:41:18.672+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.116 seconds
[2024-12-26T21:41:49.270+0000] {processor.py:153} INFO - Started process (PID=49955) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:41:49.271+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:41:49.271+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:41:49.271+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:41:49.290+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:41:49.304+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:41:49.304+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:41:49.319+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:41:49.319+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:41:49.337+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.070 seconds
[2024-12-26T21:42:23.289+0000] {processor.py:153} INFO - Started process (PID=50046) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:42:23.289+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:42:23.291+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:42:23.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:42:23.303+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:42:23.321+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:42:23.321+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:42:23.335+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:42:23.335+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:42:23.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.072 seconds
[2024-12-26T21:58:06.352+0000] {processor.py:153} INFO - Started process (PID=50120) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:58:06.353+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:58:06.354+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:58:06.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:58:06.373+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:58:06.404+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:58:06.404+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:58:06.433+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:58:06.432+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:58:06.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.107 seconds
[2024-12-26T21:58:37.206+0000] {processor.py:153} INFO - Started process (PID=50211) to work on /opt/airflow/dags/consumer.py
[2024-12-26T21:58:37.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T21:58:37.207+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:58:37.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T21:58:37.224+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T21:58:37.238+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:58:37.238+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T21:58:37.253+0000] {logging_mixin.py:137} INFO - [2024-12-26T21:58:37.253+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T21:58:37.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.063 seconds
[2024-12-26T22:15:36.683+0000] {processor.py:153} INFO - Started process (PID=50301) to work on /opt/airflow/dags/consumer.py
[2024-12-26T22:15:36.684+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T22:15:36.684+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:15:36.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T22:15:36.707+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T22:15:36.736+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:15:36.735+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T22:15:36.758+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:15:36.758+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T22:15:36.787+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.106 seconds
[2024-12-26T22:32:12.361+0000] {processor.py:153} INFO - Started process (PID=50376) to work on /opt/airflow/dags/consumer.py
[2024-12-26T22:32:12.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T22:32:12.363+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:32:12.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T22:32:12.385+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T22:32:12.417+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:32:12.417+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T22:32:12.436+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:32:12.436+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T22:32:12.461+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.103 seconds
[2024-12-26T22:50:12.039+0000] {processor.py:153} INFO - Started process (PID=50467) to work on /opt/airflow/dags/consumer.py
[2024-12-26T22:50:12.040+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T22:50:12.041+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:50:12.041+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T22:50:12.064+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T22:50:12.094+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:50:12.094+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T22:50:12.114+0000] {logging_mixin.py:137} INFO - [2024-12-26T22:50:12.114+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T22:50:12.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.111 seconds
[2024-12-26T23:06:33.701+0000] {processor.py:153} INFO - Started process (PID=50558) to work on /opt/airflow/dags/consumer.py
[2024-12-26T23:06:33.702+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T23:06:33.703+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:06:33.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T23:06:33.721+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T23:06:33.740+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:06:33.740+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T23:06:33.766+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:06:33.765+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T23:06:33.792+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.094 seconds
[2024-12-26T23:23:52.101+0000] {processor.py:153} INFO - Started process (PID=50649) to work on /opt/airflow/dags/consumer.py
[2024-12-26T23:23:52.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T23:23:52.103+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:23:52.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T23:23:52.129+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T23:23:52.152+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:23:52.152+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T23:23:52.179+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:23:52.179+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T23:23:52.211+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.114 seconds
[2024-12-26T23:26:16.579+0000] {processor.py:153} INFO - Started process (PID=50724) to work on /opt/airflow/dags/consumer.py
[2024-12-26T23:26:16.580+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T23:26:16.581+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:26:16.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T23:26:16.600+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T23:26:16.612+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:26:16.612+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T23:26:16.624+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:26:16.624+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T23:26:16.635+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.060 seconds
[2024-12-26T23:43:56.106+0000] {processor.py:153} INFO - Started process (PID=50815) to work on /opt/airflow/dags/consumer.py
[2024-12-26T23:43:56.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T23:43:56.109+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:43:56.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T23:43:56.130+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T23:43:56.158+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:43:56.158+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T23:43:56.179+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:43:56.179+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T23:43:56.224+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.123 seconds
[2024-12-26T23:55:01.591+0000] {processor.py:153} INFO - Started process (PID=50906) to work on /opt/airflow/dags/consumer.py
[2024-12-26T23:55:01.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T23:55:01.592+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:55:01.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T23:55:01.606+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T23:55:01.618+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:55:01.618+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T23:55:01.629+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:55:01.629+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T23:55:01.638+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.049 seconds
[2024-12-26T23:55:32.551+0000] {processor.py:153} INFO - Started process (PID=50997) to work on /opt/airflow/dags/consumer.py
[2024-12-26T23:55:32.552+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2024-12-26T23:55:32.553+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:55:32.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2024-12-26T23:55:32.572+0000] {processor.py:753} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2024-12-26T23:55:32.588+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:55:32.588+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-12-26T23:55:32.601+0000] {logging_mixin.py:137} INFO - [2024-12-26T23:55:32.601+0000] {dag.py:3441} INFO - Setting next_dagrun for consumer to None, run_after=None
[2024-12-26T23:55:32.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/consumer.py took 0.068 seconds
